services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backups:/app/backups
      - ./database:/app/database
      - ./logs:/var/log     
      - ./utils:/app/utils      
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei      
    dns:
      - 192.168.1.3
      - 192.168.1.2
      - 1.1.1.1
      - 9.9.9.9
    restart: unless-stopped
