services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backups:/app/backups
      - ./database:/app/database
      - ./logs:/var/log     
      - ./utils:/app/utils      
    env_file:
      - .env      
    restart: unless-stopped
